language: c
sudo: required

before_install:
    - sudo apt-get clean && sudo apt-get update
    - sudo apt-get install gcc-4.6 gfortran-4.6 hdf5-tools libmpich1.0-dev libhdf5-mpich-dev
    - sudo ln -s /usr/bin/gfortran-4.6 /usr/bin/gfortran
    - which gfortran

script:
    - pwd
    - cd ED/build/
    - install.sh --kind B --platform gfortran
